import React, { forwardRef } from 'react';
import SkillGraph from './SkillGraph';
import ProjectTimeline from './ProjectTimeline';

const ResumePDF = forwardRef(({ userData, skills, projects }, ref) => {
  return (
    <div ref={ref} className="bg-white p-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8 border-b-2 border-gray-200 pb-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          {userData?.name || 'Your Name'}
        </h1>
        <p className="text-lg text-gray-600 mb-2">
          {userData?.title || 'Software Developer'}
        </p>
        <div className="text-sm text-gray-500 space-x-4">
          <span>{userData?.email || 'email@example.com'}</span>
          <span>•</span>
          <span>{userData?.phone || '+1 (555) 123-4567'}</span>
          <span>•</span>
          <span>{userData?.location || 'San Francisco, CA'}</span>
        </div>
      </div>

      {/* Skills Section */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Skills & Progression</h2>
        <div className="border border-gray-200 rounded-lg p-4">
          <SkillGraph data={skills} width={500} height={250} />
        </div>
      </div>

      {/* Projects Section */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Projects & Experience</h2>
        <div className="space-y-4">
          {projects?.map((project) => (
            <div key={project.id} className="border border-gray-200 rounded-lg p-4">
              <div className="flex justify-between items-start mb-2">
                <h3 className="text-lg font-semibold text-gray-900">{project.title}</h3>
                <span className="text-sm text-gray-500">
                  {new Date(project.startDate).toLocaleDateString()} - {new Date(project.endDate).toLocaleDateString()}
                </span>
              </div>
              <div className="flex flex-wrap gap-2 mb-2">
                {project.tags.map((tag) => (
                  <span key={tag} className="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
                    {tag}
                  </span>
                ))}
              </div>
              <p className="text-gray-700 text-sm">{project.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-gray-500 mt-8 pt-6 border-t border-gray-200">
        <p>Generated by SkillPlot - Visual Resume & Career Mapper</p>
        <p>Generated on {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
});

ResumePDF.displayName = 'ResumePDF';

export default ResumePDF; 